language: go
sudo: false
go_import_path: github.com/go-session/gin-session
go:
  - "1.19"
before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
